### ISSUE TITLE
TypeError in util at import

### ISSUE THREAD

**Issue by JDTeske** [qutech/filter_functions#26]
At import util throws an uncatched TypeError. The error is thrown in a try catch block so my hotfix was to include TypeError in the exect statement.

Same issue occured on two different machienes. Setting up the environment by:

conda create -n myenv python=3.7
conda activate myenv
conda install numpy cython matplotlib pytest pytest-cov jupyter notebook spyder scipy
conda config --append channels conda-forge
conda install qutip
conda install pandas simanneal
pip install filter_functions

Error Message:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-b5b72fbc51ca> in <module>
      1 import numpy as np
      2 from qsim.matrix import DenseOperator
----> 3 from qsim.solver_algorithms import SchroedingerSolver
      4 
      5 
c:\users\programmer\documents\qsim\labcourseroot\qsim\qsim\solver_algorithms.py in <module>
     63 from abc import ABC, abstractmethod
     64 
---> 65 from filter_functions import pulse_sequence
     66 from filter_functions import plotting
     67 from filter_functions import basis
~\AppData\Local\conda\conda\envs\jupyter_server\lib\site-packages\filter_functions\__init__.py in <module>
     21 """Package for efficient calculation of generalized filter functions"""
     22 
---> 23 from . import analytic, basis, numeric, plotting, pulse_sequence, util
     24 from .basis import Basis
     25 from .numeric import (error_transfer_matrix, infidelity,
~\AppData\Local\conda\conda\envs\jupyter_server\lib\site-packages\filter_functions\basis.py in <module>
     52 from sparse import COO
     53 
---> 54 from .util import P_np, remove_float_errors, tensor
     55 
     56 __all__ = ['Basis', 'expand', 'ggm_expand', 'normalize']
~\AppData\Local\conda\conda\envs\jupyter_server\lib\site-packages\filter_functions\util.py in <module>
    153         return ''
    154 
--> 155     _NOTEBOOK_NAME = _get_notebook_name()
    156 except ImportError:
    157     _NOTEBOOK_NAME = ''
~\AppData\Local\conda\conda\envs\jupyter_server\lib\site-packages\filter_functions\util.py in _get_notebook_name()
    147                                     params={'token': ss.get('token', '')})
    148             for nn in json.loads(response.text):
--> 149                 if nn['kernel']['id'] == kernel_id:
    150                     relative_path = nn['notebook']['path']
    151                     return os.path.join(ss['notebook_dir'], relative_path)
TypeError: string indices must be integers

**Comment by thangleiter** [comment]
I unfortunately cannot reproduce this, but it has been noted in the [Jupyter issue](https://github.com/jupyter/notebook/issues/1000#issuecomment-502889126) the relevant function is from.

The easiest fix is just to catch the error, since apparently it arises when the jupyter server is queried with a wrong token in line 146--147.

**Comment by thangleiter** [comment]
@JDTeske, can you check if https://github.com/qutech/filter_functions/pull/28 fixes the issue on your side?
